// day18/my-first-angular-app/src/app/components/badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-badge',
  template: `
    <button (click)="handleClick()" type="button" class="btn btn-primary">
        {{caption}} <span class="badge text-bg-secondary">{{count}}</span>
    </button>
  `,

})
export class BadgeComponent {

  count: number= 0;
  @Input('caption')caption: string = "Default Caption"

  handleClick(){
    console.log('click event from angular button');
    this.count++;
  }
}

// day10/mern-app/my-react-app/src/components/Badge.jsx
import { useState } from "react";

function Badge (prop){

    // let count = 34;
    const [count, setCount] = useState(0);
    
    function handleClick(){
        console.log("Button clicked!");
        // prop.caption = "ABC"
        setCount(count + 1);
        // count++;
        console.log(count);
        
    }
    
    // console.log('Rendering UI .... ')
    return (
        <button onClick={handleClick} type="button" className="btn btn-primary">
            {prop.caption} <span className="badge text-bg-secondary">{count}</span>
        </button>
    )
}

export default Badge;
