// day9/mern-app/my-frontend-app/src/components/ViewEmployees.jsx
import { useEffect, useState } from "react";

const ViewEmployees = () => {

    const [employees, setEmployees] = useState([])

    useEffect(() => {
        fetch('http://localhost:3000/api/v1/employees/')
            .then(res => res.json())
            .then(data => {
                setEmployees(data);
            })
    }, [])

    let listEmployees = employees.map((employee, i) => {
        return (
            <tr key={i}>
                <th scope="row">{i + 1}</th>
                <td>{employee.name}</td>
                <td>{employee.salary}</td>
                <td>@mdo</td>
            </tr>
        )
    })

    return (
        <div>
            <table className="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>

                    {listEmployees}
                </tbody>
            </table>
        </div>
    )

}
export default ViewEmployees;

// day18/my-first-angular-app/src/app/components/viewemployees/viewemployees.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { CardComponent } from '../card/card.component';
import { NgFor } from '@angular/common';
import { Employee } from './Employee';

@Component({
  selector: 'app-viewemployees',
  imports: [NgFor],
  templateUrl: './viewemployees.component.html',
  styleUrl: './viewemployees.component.css'
})
export class ViewemployeesComponent implements OnInit{

  constructor(private http: HttpClient) { }

  employees: Array<Employee> = [];

  ngOnInit(): void {
    console.log('On compoennt load...');

    // http call
    this.http.get('http://localhost:3000/api/v1/employees').subscribe((data:any) => {
      console.log(data);
      this.employees = data;
    });
    
  }

}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Salary</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        <!-- @for (employee of employees; track employee) { -->
      <tr *ngFor="let employee of employees; index as i">
        <th scope="row">{{i+1}}</th>
        <td>{{employee.name}}</td>
        <td>{{employee.salary}}</td>
        <td>mdo</td>
      </tr>
    <!-- } -->
    </tbody>
  </table>
